@startsalt
scale 2
{
  {+
  <&person> Нікнейм користувача | "MyName"
  <&file> Назва конференції | "Нова конференція"
  <&pencil> Тема конференції | "Обговорення проекту"

  --

  {<b>Учасники конференції:}
  {
    [ ] Іван
    [X] Олена
    [ ] Сергій
    [X] Наталія
    [ ] Андрій
  }

  [Підтвердити]

  --

  [<&circle-x> Відмінити] | [<&account-login> Почати відео-конференцію]
  }
}
@endsalt
